/** @format */

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Cats App</h1>

        <p className={styles.description}>
          Get started by clicking on the following links
        </p>

        <div className={styles.grid}>
          <a href='/breeds' className={styles.card}>
            <h2>Breeds &rarr;</h2>
            <p>Find in depth about breeds.</p>
          </a>

          <a href='/categories' className={styles.card}>
            <h2>Categories &rarr;</h2>
            <p>Learn different categories</p>
          </a>

          <a href='favourites' className={styles.card}>
            <h2>Favourites &rarr;</h2>
            <p>Discover your favourites</p>
          </a>
        </div>
      </main>
    </div>
  );
}
